[package]
name = "puzzella-puzzle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
puzzella-core.workspace = true
bevy_asset.workspace = true
bevy_ecs.workspace = true
bevy_log.workspace = true
bevy_math.workspace = true
bevy_mesh.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rayon.workspace = true
lyon.workspace = true
lyon_tessellation.workspace = true

[features]
default = []
cpu-picking-debug = []
