[package]
name = "puzzella-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
puzzella-game.workspace = true
puzzella-core.workspace = true
puzzella-puzzle.workspace = true
bevy.workspace = true
bevy_egui.workspace = true
ab_glyph.workspace = true
rfd.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock"] }
image.workspace = true
fluent-bundle = "0.16"
unic-langid = "0.9"
sys-locale = "0.3"
serde.workspace = true
rand.workspace = true
zeroize.workspace = true

[features]
default = []
gns = ["puzzella-game/gns"]
rendezvous = ["gns", "puzzella-game/rendezvous"]

[dev-dependencies]
serde_json = "1"
tempfile = "3"
crossbeam.workspace = true
fluent-syntax = "0.12"
